<?xml version="1.0" encoding="utf-8"?>

<Project>
	
	<!-- Target for Release configuration -->
	<Target Name="CopyDllToReleaseDirectory" AfterTargets="Build" Condition="('$(Configuration)' == 'Release' Or '$(Configuration)' == 'Release Final') And '$(EnableReleaseCopy)' == 'true'">
		<PropertyGroup>
			<DestinationRoot>G:\WebStatic\dirlist\SelfReleases\Build</DestinationRoot>
			<GameDirectoryName>$([System.IO.Path]::GetFileName($(GameDirectory)))</GameDirectoryName>
			<DestinationDirectory>$(DestinationRoot)\$(GameDirectoryName)\$(MSBuildProjectName)</DestinationDirectory>
			<OutputAssemblyName>$(OutputPath)$(AssemblyName)</OutputAssemblyName>
			<BuildTargetDestinationFile>$(DestinationDirectory)\BuildTarget.txt</BuildTargetDestinationFile>
		</PropertyGroup>

		<MakeDir Directories="$(DestinationDirectory)" />

		<Message Text="Copying '$(OutputAssemblyName).dll' -> '$(DestinationDirectory)\$(AssemblyName).dll'" Importance="high" />
		<Copy SourceFiles="$(OutputAssemblyName).dll" DestinationFolder="$(DestinationDirectory)" />
		
		<WriteLinesToFile File="$(BuildTargetDestinationFile)" Lines="$(GameDirectory)" Overwrite="true" />
	</Target>

	<!-- Target for Release Final configuration -->
	<Target Name="CopyDllToReleaseFinalDirectory" AfterTargets="Build" Condition="'$(Configuration)' == 'Release Final' And '$(EnableReleaseCopy)' == 'true'">
		<PropertyGroup>
			<FinalDestinationRoot>G:\WebStatic\dirlist\SelfReleases\Beat Saber</FinalDestinationRoot>
			<FinalDestinationDirectory>$(FinalDestinationRoot) $(GameDirectoryName)</FinalDestinationDirectory>
			<FinalOutputAssemblyName>$(OutputPath)$(AssemblyName)</FinalOutputAssemblyName>
		</PropertyGroup>

		<MakeDir Directories="$(FinalDestinationDirectory)" />

		<Message Text="Copying '$(FinalOutputAssemblyName).dll' -> '$(FinalDestinationDirectory)\$(AssemblyName).dll'" Importance="high" />
		<Copy SourceFiles="$(FinalOutputAssemblyName).dll" DestinationFolder="$(FinalDestinationDirectory)" />
	</Target>
</Project>
